version: '3'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    hostname: web
    volumes:
     - ./web:/code

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
     - "80:80"
